- name: Copy multiple files to EC2 instance
  hosts: ec2
  become: true

  tasks:
    - name: Copy key files to remote machine
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/home/ubuntu/{{ item | basename }}"
        owner: ubuntu
        group: ubuntu
        mode: '600'
      loop:
        - konecta_task2-kp.pem
        - konecta_task2_frontend_kp.pem
        - konecta_task2_docker_kp.pem
